version: '3.8'
services:
    app:
        build: .
        depends_on:
           
            - postgres
        ports:
            - "7000:7000"
        volumes:
           
            - ./:/usr/src/app/
    postgres:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=bhumigres
            - POSTGRES_DB=students
        ports:
            - "5432:5432"
        volumes:
            - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

  