version: '3.8'
services:
    app:
        build:
            dockerfile: Dockerfile
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app/
            - '/usr/src/app/node_modules'
        ports:
            - "3000:3000"
    postgres:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=bhumigres
            - POSTGRES_DB=students
        volumes:
            - './init:/docker-entrypoint-initdb.d/'
